_version: 2
admin:
  active: true
  apikey: B5CB35E4D234410EBDEC15ACB63F79AE
  groups:
  - users
  - admins
  password: $argon2id$v=19$m=65536,t=3,p=4$G8O4d+4d43yv1XqPcW4tRQ$BySTT6Q2tRbjZg4Q6Y+BwMEEIfHhxJEh1T+wYHpIYyw
  permissions: []
  roles:
  - user
  - admin
  settings: {}
